easy_regist/urls.py
from django.conf.urls import url
from . import views

app_name = 'easy_regist'

urlpatterns = [

    # トップページ
    url(r'^$', views.TopPageView.as_view(), name='index'),

    # マイページ機能
    url(r'^mypage/$', views.MyPageView.as_view(), name='mypage'),
    url(r'^user_update/(?P<pk>[0-9]+)/$',
        views.UserUpdateView.as_view(), name='user_update'),
    url(r'^change_password/$', views.PasswordChangeView.as_view(),
        name='change_password'),
    url(r'^change_password_done/$', views.PasswordChangeDoneView.as_view(),
        name='change_password_done'),

    # 会員登録
    url(r'^create/$', views.CreateUserView.as_view(), name='create'),
    url(r'^create_done/$', views.CreateDoneView.as_view(), name='create_done'),
    url(r'^create_complete/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]\
        {1,13}-[0-9A-Za-z]{1,20})/$',
        views.CreateCompleteView.as_view(), name='create_complete'),

    # ログイン、ログアウト
    url(r'^login/$', views.LoginView.as_view(), name='login'),
    url(r'^logout/$', views.LogoutView.as_view(), name='logout'),

    # パスワード忘れ
    url(r'^password_reset/$', views.PasswordResetView.as_view(),
        name='password_reset'),
    url(r'^password_reset_done/$', views.PasswordResetDoneView.as_view(),
        name='password_reset_done'),
    url(r'^password_reset_confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>\
        [0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.PasswordResetConfirmView.as_view(),
        name='password_reset_confirm'),
    url(r'^password_reset_complete/$',
        views.PasswordResetCompleteView.as_view(),
        name='password_reset_complete'),
]

easy_regist/templates/easy_regist/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
  <head>
    <!-- Required meta tags always come first -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'easy_regist/css/main.css' %}">

  </head>
  <body>

    <nav class="navbar navbar-toggleable-md navbar-inverse bg-primary">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
        &#9776;
      </button>
      
      
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <div class="container">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
             <a class="nav-item nav-link" href="{% url 'easy_regist:index' %}">トップ</a>
          </li>
          {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-item nav-link" href="{% url 'easy_regist:mypage' %}">
              ようこそ、{{ user.email }}！マイページへ
            </a>
          </li>
          <li>
            <a class="nav-item nav-link" href="{% url 'easy_regist:logout' %}">ログアウト</a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-item nav-link" href="{% url 'easy_regist:login' %}">
            ようこそ、ゲスト！ログインはこちら
          </a>
          </li>
          {% endif %}
        </ul>
      </div>
      </div>
    </nav>

    {% block content %} {% endblock %}

    <!-- jQuery first, then Tether, then Bootstrap JS. -->
    <script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>
  </body>
</html>

easy_regist/templates/easy_regist/change_password.html
{% extends "easy_regist/base.html" %}
{% block content %}
<div class="container">
  <div class="center">
    <h1>ユーザ情報</h1>
    <p class="lead">ログイン中のユーザデータを表示します</p>
  </div>

  <form action="" method="POST">
  <table class="table">
    <thead class="thead-inverse">
      <tr>
        <th>項目</th>
        <th>入力欄</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>古いパスワード</td>
        <td>
          {{ form.old_password }}
          {{ form.old_password.errors }}
        </td>
      </tr>
      <tr>
        <td>パスワード</td>
        <td>
          {{ form.new_password1 }}
          {{ form.new_password1.errors }}
        </td>
      </tr>
      <tr>
        <td>パスワード（確認）</td>
        <td>
          {{ form.new_password2 }}
          {{ form.new_password2.errors }}
        </td>
      </tr>
    </tbody>
  </table>
  {% csrf_token %}
  <button type="submit" class="btn btn-outline-primary">変更</button>
  <a href="{% url 'easy_regist:mypage' %}" class="btn btn-outline-primary">戻る</a>
  </form>
  

</div><!-- /.container -->
{% endblock %}

easy_regist/templates/easy_regist/change_password_done.html
{% extends "easy_regist/base.html" %}
{% block content %}
<div class="container">
  <div class="center">
    <h1>ユーザ情報</h1>
    <p class="lead">パスワードを変更しました</p>
  </div>

</div><!-- /.container -->
{% endblock %}

easy_regist/templates/easy_regist/create.html
{% extends "easy_regist/base.html" %}
{% block content %}
<div class="container">
  <div class="center">
    <h1>ユーザ登録</h1>
  </div>

　　<form action="" method="POST">
	<div class="row">
	  <div class="col-sm-10 offset-sm-1">
　　　　    <div class="card">
  　　　　    <div class="card-block">

  			<div class="row">
  			  <div class="col-12">
  			    <div class="form-group">
  			  	  {{ form.email }}
  			  	  {{ form.email.errors }}
  			  	</div>
  			  </div>
  			</div>
  			<div class="row">
  			  <div class="col-12 col-sm-6">
  			    <div class="form-group">
  			  	  {{ form.password1 }}
  			  	  {{ form.password1.errors }}
  			  	</div>
  			  </div>
   			  <div class="col-12 col-sm-6">
   			    <div class="form-group">
  			  	  {{ form.password2 }}
  			  	  {{ form.password2.errors }}
  			  	</div>
  			  </div>
  			</div>
    		<div class="row">
  			  <div class="col-12 col-sm-6">
  			    <div class="form-group">
  			  	  {{ form.first_name }}
  			  	</div>
  			  </div>
   			  <div class="col-12 col-sm-6">
   			    <div class="form-group">
  			  	  {{ form.last_name }}
  			  	</div>
  			  </div>
  			</div>
	  　　    {% csrf_token %}
	  　　    <button type="submit" class="btn btn-lg btn-block btn-outline-primary">会員登録</button>
  　　　　    </div>
　　　　    </div>
      </div>
    </div>
　　</form>

</div>
{% endblock %}

easy_regist/templates/easy_regist/create_complete.html
{% extends "easy_regist/base.html" %}
{% block content %}
<div class="container">
  <div class="center">
    <h1>ユーザ登録</h1>
    <p class="lead">会員登録がおわりました</p>
  </div>
</div><!-- /.container -->
{% endblock %}

easy_regist/templates/easy_regist/create_done.html
{% extends "easy_regist/base.html" %}
{% block content %}
<div class="container">
  <div class="center">
    <h1>ユーザ登録</h1>
    <p class="lead">仮登録しました。本登録はメールをみてね</p>
  </div>
</div><!-- /.container -->
{% endblock %}

easy_regist/templates/easy_regist/index.html
{% extends "easy_regist/base.html" %}
{% block content %}
<div class="container">
  <div class="center">
    <h1>トップページ</h1>
    <p class="lead">Bootstrap4を使っています。</p>
  </div>
</div><!-- /.container -->
{% endblock %}

easy_regist/templates/easy_regist/info.html
{% extends "easy_regist/base.html" %}
{% block content %}
<div class="container">
  <div class="center">
    <h1>ユーザ情報</h1>
    <p class="lead">ログイン中のユーザデータを表示します</p>
  </div>

  <table class="table">
    <thead class="thead-inverse">
      <tr>
        <th>名前・説明</th>
        <th>templateでの呼び出し方</th>
        <th>ログインユーザのデータ</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>メール</td>
        <td>{% verbatim %} {{ user.email }} {% endverbatim %} </td>
        <td>{{ user.email }}</td>
      </tr>
      <tr>
        <td>姓</td>
        <td>{% verbatim %} {{ user.first_name }} {% endverbatim %} </td>
        <td>{{ user.first_name }}</td>
      </tr>
      <tr>
        <td>名</td>
        <td>{% verbatim %} {{ user.last_name }} {% endverbatim %} </td>
        <td>{{ user.last_name }}</td>
      </tr>
      <tr>
        <td>adminサイトにアクセスできるか</td>
        <td>{% verbatim %} {{ user.is_staff }} {% endverbatim %} </td>
        <td>{{ user.is_staff }}</td>
      </tr>
      <tr>
        <td>アカウントが有効か（ログインできるか）</td>
        <td>{% verbatim %} {{ user.is_active }} {% endverbatim %} </td>
        <td>{{ user.is_active }}</td>
      </tr>
    </tbody>
  </table>
  <a href="{% url 'easy_regist:user_update' user.pk %}" class="btn btn-outline-primary">ユーザ情報の変更</a>
  <a href="{% url 'easy_regist:change_password' %}" class="btn btn-outline-primary">パスワードの変更</a>

</div><!-- /.container -->
{% endblock %}

easy_regist/templates/easy_regist/login.html
{% extends "easy_regist/base.html" %}
{% block content %}
<div class="container">
  <div class="center">
    <h1>ログインページ</h1>
  </div>

  <div class="card-group">
    <div class="card card-outline-primary">
      <div class="card-block">
        <form action="{% url 'easy_regist:login' %}" method="POST">
  		  <p>{{ form.non_field_errors }}</p>
	    　　{{ form.username }}
	    　　{{ form.password }}
	  　　  {% csrf_token %}
	  	  <input type="hidden" name="next" value="{{ next }}" />
	  　　  <button type="submit" class="btn btn-lg btn-block btn-outline-primary">
	        ログイン
	      </button>
	    </form>
      </div>
    </div>
    <div class="card card-outline-primary">
      <div class="card-block">
        <a class="btn btn-lg btn-block btn-outline-primary" href="{% url 'easy_regist:create' %}">
          会員登録
        </a>
        <a class="btn btn-lg btn-block btn-outline-primary" href="{% url 'easy_regist:password_reset' %}">
          パスワードを忘れた
        </a>
      </div>
    </div>

  </div><!-- /.card-group -->
　　
</div><!-- /.container -->
{% endblock %}

easy_regist/templates/easy_regist/password_reset_complete.html
{% extends "easy_regist/base.html" %}
{% block content %}
<div class="container">
  <div class="center">
    <h1>パスワードリセットページ</h1>
    <p class="lead">パスワードをリセットしました。</p>
  </div>
</div><!-- /.container -->
{% endblock %}

easy_regist/templates/easy_regist/password_reset_confirm.html
{% extends "easy_regist/base.html" %}
{% block content %}
<div class="container">
  <div class="center">
    <h1>パスワードリセットページ</h1>
    <p class="lead">新パスワードを入力してください</p>
  </div>

　　<form action="" method="POST">
  <div class="row">
    <div class="col-sm-8 offset-sm-2">
　　　　    <div class="card">
  　　　　    <div class="card-block">
            <div class="form-group">
              {{ form.new_password1 }}
              {{ form.new_password1.errors }}
            </div>
            <div class="form-group">
              {{ form.new_password2 }}
              {{ form.new_password2.errors }}
            </div>
    　　    {% csrf_token %}
    　　    <button type="submit" class="btn btn-lg btn-block btn-outline-primary">送信</button>
  　　　　    </div>
　　　　    </div>
      </div>
    </div>
　　</form>
</div><!-- /.container -->
{% endblock %}

easy_regist/templates/easy_regist/password_reset_done.html
{% extends "easy_regist/base.html" %}
{% block content %}
<div class="container">
  <div class="center">
    <h1>パスワードリセットページ</h1>
    <p class="lead">メールアドレスにパスワード初期化ページのURLを送付しました。</p>
  </div>
</div><!-- /.container -->
{% endblock %}

easy_regist/templates/easy_regist/password_reset_form.html
{% extends "easy_regist/base.html" %}
{% block content %}
<div class="container">
  <div class="center">
    <h1>パスワードリセットページ</h1>
    <p class="lead">メールアドレスを入力してください。</p>
  </div>
　　<form action="" method="POST">
  <div class="row">
    <div class="col-sm-8 offset-sm-2">
　　　　    <div class="card">
  　　　　    <div class="card-block">
            <div class="form-group">
              {{ form.email }}
            </div>
    　　    {% csrf_token %}
    　　    <button type="submit" class="btn btn-lg btn-block btn-outline-primary">送信</button>
  　　　　    </div>
　　　　    </div>
      </div>
    </div>
　　</form>
</div><!-- /.container -->
{% endblock %}

easy_regist/templates/easy_regist/user_update.html
{% extends "easy_regist/base.html" %}
{% block content %}
<div class="container">
  <div class="center">
    <h1>ユーザ情報</h1>
    <p class="lead">ログイン中のユーザデータを表示します</p>
  </div>

  <form action="" method="POST">
  <table class="table">
    <thead class="thead-inverse">
      <tr>
        <th>項目</th>
        <th>入力欄</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>メールアドレス</td>
        <td>
          {{ form.email }}
          {{ form.email.errors }}
        </td>
      </tr>
      <tr>
        <td>姓</td>
        <td>
          {{ form.first_name }}
          {{ form.first_name.errors }}
        </td>
      </tr>
      <tr>
        <td>名</td>
        <td>
          {{ form.last_name }}
          {{ form.last_name.errors }}
        </td>
      </tr>
    </tbody>
  </table>
  {% csrf_token %}
  <button type="submit" class="btn btn-outline-primary">変更</button>
  <a href="{% url 'easy_regist:mypage' %}" class="btn btn-outline-primary">戻る</a>
  </form>
  

</div><!-- /.container -->
{% endblock %}